"""initial schema

Revision ID: a3ea8e6c052e
Revises: 
Create Date: 2026-09-01 00:28:43.287666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3ea8e6c052e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.Column('funded_cents', sa.Integer(), nullable=False),
    sa.Column('committed_cents', sa.Integer(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('provider_mode', sa.String(), nullable=False),
    sa.CheckConstraint('budget_cents >= 0', name='ck_campaign_budget_nonneg'),
    sa.CheckConstraint('committed_cents <= funded_cents', name='ck_campaign_committed_le_funded'),
    sa.CheckConstraint('committed_cents >= 0', name='ck_campaign_committed_nonneg'),
    sa.CheckConstraint('funded_cents >= 0', name='ck_campaign_funded_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_subject', sa.String(), nullable=False),
    sa.Column('declared_languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subject')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('event_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('blocked_words', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('accepted_answers', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('distractors', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('array_length(accepted_answers, 1) >= 2', name='ck_card_accepted_answers_min2'),
    sa.CheckConstraint('array_length(blocked_words, 1) = 4', name='ck_card_blocked_words_exactly4'),
    sa.CheckConstraint('array_length(distractors, 1) = 3', name='ck_card_distractors_exactly3'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consent_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('provider_mode', sa.String(), nullable=False),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('CREATED', 'SUBMITTED', 'PENDING', 'PAID', 'FAILED', name='payment_state'), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_cents > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_payment_idempotency_key')
    )
    op.create_table('contributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('declared_language', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'RECORDED', 'QUALITY_PASSED', 'OPEN', 'UNDERSTOOD', 'REVIEW_REQUIRED', 'VOIDED', 'EXPIRED', 'CORPUS_ELIGIBLE', 'UNVALIDATED', name='contribution_state'), nullable=False),
    sa.Column('audio_key', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('quality_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('verifier_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('LEARNER_MCQ', 'PROFICIENT_VERIFIER', name='assignment_mode'), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_normalised', sa.Text(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('violation_vote', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['verifier_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_id', 'verifier_id', name='uq_assignment_contribution_verifier')
    )
    op.create_table('eligibility_decisions',
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('understood', sa.Boolean(), nullable=False),
    sa.Column('corpus_eligible', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('receipts',
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('semantic_label', sa.String(), nullable=False),
    sa.Column('decision_evidence_json', sa.Text(), nullable=False),
    sa.Column('reward_rule_version', sa.String(), nullable=False),
    sa.Column('consent_version', sa.String(), nullable=False),
    sa.Column('payment_state', sa.String(), nullable=False),
    sa.Column('settlement_currency', sa.String(), nullable=False),
    sa.Column('currency_disclosure_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_table('reward_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contribution_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name='ck_reward_amount_positive'),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_id', 'user_id', 'type', name='uq_reward_contribution_user_type'),
    sa.UniqueConstraint('idempotency_key', name='uq_reward_idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_events')
    op.drop_table('receipts')
    op.drop_table('eligibility_decisions')
    op.drop_table('assignments')
    op.drop_table('contributions')
    op.drop_table('payment_attempts')
    op.drop_table('consent_grants')
    op.drop_table('cards')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('campaigns')
    # ### end Alembic commands ###

    # Manually added -- caught by a real downgrade/re-upgrade roundtrip test
    # (starter/backend/tests/test_migrations.py) run against a real
    # PostgreSQL 16 instance: Alembic's autogenerate drops tables that use
    # PostgreSQL ENUM types but does NOT drop the ENUM types themselves
    # (a known alembic/SQLAlchemy limitation -- op.drop_table() does not
    # cascade to sa.Enum-backed CREATE TYPE). Without these lines, downgrade
    # followed by upgrade fails with "type ... already exists" the second
    # time the DDL runs, which is exactly the demo-reset failure mode Gate H
    # explicitly needs to survive ("Judge-only demo survives a reset,
    # twice"). Drop order doesn't matter for types (no inter-type FKs).
    sa.Enum(name='payment_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='contribution_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='assignment_mode').drop(op.get_bind(), checkfirst=True)
